spring.application.name=task-manager

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/task_manager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:task_manager_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:task_manager_password}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
